seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "./output/ckpt/LJSpeech_delightfultts_upp_adaspeech_no_prosody_loss"
  log_path: "./output/log/LJSpeech_delightfultts_upp_adaspeech_no_prosody_loss"
  result_path: "./output/result/LJSpeech_delightfultts_upp_adaspeech_no_prosody_loss"
optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 25000
duration:
  binarization_start_steps: 6000
  binarization_loss_enable_steps: 18000
  binarization_loss_warmup_steps: 10000
prosody:
  gmm_mdn_beta: 0.02
